version: 2

sources:
  - name: erp_northwind
    description: sistema de dados de venda da Northwind
    database: FEA24_9
    schema: raw_northwind  
    tables:
      - name: employee
        description: tabela fonte com informações dos funcionários da Northwind
        columns:
          - name: id
            data_tests:
              - unique
              - not_null

      - name: product
        description: tabela fonte com informações dos produtos da Northwind
      - name: category
        description: tabela fonte com informações das categorias de produtos da Northwind
      - name: supplier
        description: tabela fonte com informações dos fornecedores da Northwind
      - name: _order_
        description: tabela fonte com informações dos fornecedores da Northwind
      - name: orderdetail
        description: tabela fonte com informações dos fornecedores da Northwind
